### ISSUE TITLE
Aivu (Azata Dragon pet)

### ISSUE THREAD

**Issue by megahell84** [BarleyFlour/RespecMod#112]
Hello ! 

The mod doesn't allow respec for Aivu :( 

Is there a way that we can respec her as well ? 

Because as of the 1.0.7f version of the game, almost all her skills are messed up (unarmed combat ? dagger ? WTF !?).

Plus there are many levels that seem to have been skipped : no skill were taken for her.

Maybe it's intended by the developers, but as for now she's not very useful -_-

And I don't know for you but I don't like broken (in a bad way) characters. Fortunately, that mod fixed almost all of them for me ^^

Thx !

**Comment by sotanaht1** [comment]
Levels being skipped is an issue I've been having with other companions.  Always make sure when you level up that your level progression is correct.  If it's not, I recommend saving and restarting the game, possibly installing or uninstalling the respec mod in the process (not simply disabling it).  

In my case I get the issue with companions if I level up while Respec is uninstalled, but it could actually just be a case of restarting the game (since reinstalling it requires doing that anyway).

**Comment by megahell84** [comment]
Hi ! 

I don't think the respec mod is the issue here : I installed the mod after my level up (main char lvl 10, mythic path 4, Aivu lvl 15).

I think it's more of an issue where Aivu is not exactly a classic companion, where she levels up with the main char mythic path, and not with XP like others characters.

In the base game you can't choose her stats when leveling up, and she automatically "jump" froml lvl 10 to lvl 15 when you lvl up mythic path 4 for example.

In my case, I just wish that the mod let me do that the base game doesn't : respec her properly because nearly all her skills are messed up.
