### ISSUE TITLE
Ember continues to have the Blackened penalty after respeccing out of it

### ISSUE THREAD

**Issue by AlexClark** [BarleyFlour/RespecMod#47]
Respecced from stigmatized witch to leyline witch, the blackened penalty did not go away, and is persistent after saving and reloading. Multiple subsequent respecs into other classes (like going back to stigmatized and respeccing back out, respeccing to oracle with blackened and back out, ect.) did not remove it either.

**Comment by wska** [comment]
Not the mod author but: There is a whole bunch of these problems occurring with the normal in-game respecs, so there are probably things that will have to be fixed in the main game. Another example is if you ever create or respec into a Dhampir(race), you will ALWAYS have negative energy affinity, even if you respec out of that race again. 

This particular bug could be fixed by removing said affinity using the bag of tricks mod, so something similar might be possible for Embers penalty as a temporary workaround.

But ya, these things will probably get fixed by Owlcat themselves in a while. "Probably".

**Comment by BarleyFlour** [comment]
Fixed with 1.06.2
