### ISSUE TITLE
Since WoTR patch 1.0.6d clicking the 'Submit' button to respec does nothing

### ISSUE THREAD

**Issue by KyoeiX** [BarleyFlour/RespecMod#98]
First @barleyflour - Thanks for this mod also, able to play the game the way we like :)

As the mentioned in the title:

Since WoTR patch 1.0.6d (released 2 days ago) -  clicking the 'Submit' button to respec does nothing - I just picked up Regill also, want to get him sorted out.

**Comment by rparavicini** [comment]
The problem seems to be a missing function:

[RespecWrath] System.MissingMethodException: void Kingmaker.UnitLogic.UnitProgressionData.DropLevelPlansAll()
  at RespecModBarley.Main.PreRespec (Kingmaker.EntitySystem.Entities.UnitEntityData entityData) [0x0037c] in <92662469a14145dc89169bdab9d9cd47>:0 

strangely, it worked once, right after I installed the mod, and the next time I tried it, the error occured.

**Comment by BarleyFlour** [comment]
You need to be v1.06.2 or higher as of 1.0.6d.
